### ISSUE TITLE
Crash on "Managing feeds"

### ISSUE THREAD

**Issue by mochaaP** [fbarthelery/geekttrss#21]
```log
11-29 04:08:00.937  2004  6897 I ActivityTaskManager: START u0 {cmp=com.geekorum.ttrss.free/com.geekorum.ttrss.manage_feeds.ManageFeedsActivity (has extras)} from uid 10496
11-29 04:08:00.939  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 174042980; UID 10496; state: DISABLED
11-29 04:08:00.940  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 184838306; UID 10496; state: DISABLED
11-29 04:08:00.941  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 185004937; UID 10496; state: DISABLED
11-29 04:08:00.941  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 181136395; UID 10496; state: DISABLED
11-29 04:08:00.942  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 174042936; UID 10496; state: DISABLED
11-29 04:08:00.949  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 197654537; UID 10496; state: ENABLED
11-29 04:08:00.952  2004  6897 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10496; state: DISABLED
11-29 04:08:00.963  2004  6756 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (243066046)
11-29 04:08:00.974 30561 30561 D AndroidRuntime: Shutting down VM
11-29 04:08:00.975 30561 30561 E AndroidRuntime: FATAL EXCEPTION: main
11-29 04:08:00.975 30561 30561 E AndroidRuntime: Process: com.geekorum.ttrss.free, PID: 30561
11-29 04:08:00.975 30561 30561 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.geekorum.ttrss.free/com.geekorum.ttrss.manage_feeds.ManageFeedsActivity}: java.lang.ClassNotFoundException: Didn't find class "com.geekorum.ttrss.manage_feeds.ManageFeedsActivity" on path: DexPathList[[zip file "/data/app/~~lsUGrHWyc0mzsco8PedlhA==/com.geekorum.ttrss.free-G6bNgnWhyLJCoMxFsbh31w==/base.apk"],nativeLibraryDirectories=[/data/app/~~lsUGrHWyc0mzsco8PedlhA==/com.geekorum.ttrss.free-G6bNgnWhyLJCoMxFsbh31w==/lib/arm64, /system/lib64, /system_ext/lib64]]
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3614)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3865)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2254)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7876)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.geekorum.ttrss.manage_feeds.ManageFeedsActivity" on path: DexPathList[[zip file "/data/app/~~lsUGrHWyc0mzsco8PedlhA==/com.geekorum.ttrss.free-G6bNgnWhyLJCoMxFsbh31w==/base.apk"],nativeLibraryDirectories=[/data/app/~~lsUGrHWyc0mzsco8PedlhA==/com.geekorum.ttrss.free-G6bNgnWhyLJCoMxFsbh31w==/lib/arm64, /system/lib64, /system_ext/lib64]]
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1292)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3601)
11-29 04:08:00.975 30561 30561 E AndroidRuntime: 	... 12 more
11-29 04:08:00.977  2004 31056 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-29 04:08:00.978  2004  6897 W ActivityTaskManager:   Force finishing activity com.geekorum.ttrss.free/com.geekorum.ttrss.manage_feeds.ManageFeedsActivity
11-29 04:08:00.980  2004  6897 W ActivityTaskManager:   Force finishing activity com.geekorum.ttrss.free/com.geekorum.ttrss.articles_list.ArticleListActivity
11-29 04:08:00.988  2004  2161 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-29 04:08:00.988  2004  2161 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
```

**Comment by fbarthelery** [comment]
@mochaaP Do you have any more information? Otherwise I'll close this issue

**Comment by mochaaP** [comment]
Sorry for the late response, I will capture a logcat now

**Comment by mochaaP** [comment]
Updated.

**Comment by fbarthelery** [comment]
Oups, looks like I uploaded the wrong apk when I made the release. :confused:

@mochaaP the correct one should be on [there](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.0) now

Let me know if you still experience the issue
